### ISSUE TITLE
Could not find: Select the Sideload apps radio button, selected developer mode

### ISSUE THREAD

**Issue by kalyanimsft** [microsoft/MSIX-Labs#24]
While installing the lab environment for MSIX, I was not able to find the Sideload apps radio button.
We should probably remove the reference to this if it is no longer applicable.

**Comment by anarvekar-msft** [comment]
![image](https://user-images.githubusercontent.com/84478144/130153790-cb030fe1-ea2d-4737-b340-dc73ba5fd790.png)

Maybe we have a version difference, or maybe you are missing some of the Visual Studio 2019 add ons in the set up. I am able to see the sideloading button.

**Comment by anarvekar-msft** [comment]
Turning on developer mode might also help https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
